adds field for guide navigation layout type
localgovdrupal/localgov_guides pull request #182
Opened 2024-11-28 15:01 UTC by markconroy

Closes #123 

## What does this change?

- Adds a new field called "List Layout" so editors can choose on a per-guide basis whether they want horizonal/vertical layout.
- Defaults to "Vertical (Single Column)"

![Screenshot 2024-11-28 at 14 53 02](https://github.com/user-attachments/assets/5982cf63-e0fd-4f83-9233-caad26bd3d85)

## How to test

Install Guides module
Create a guide overview and some guide pages
In Guide Overview, choose "Horizontal" or "Vertical" for the "List Layout"
Check that the Guide Nav responds accordingly **NOTE** it will need [this PR from LocalGov base](https://github.com/localgovdrupal/localgov_base/pull/665) which has the required CSS.

---
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

2024-12-09 18:30 UTC, msayoung requested changes
Causes errors on pre-existing guides. 

```InvalidArgumentException: Field localgov_guides_list_layout is unknown.```

2024-12-12 12:00 UTC, stephen-cox commented
> Causes errors on pre-existing guides.
> 
> `InvalidArgumentException: Field localgov_guides_list_layout is unknown.`

You're going to need to either check the field exists before using it or add an update hook to install this into existing sites.

2024-12-13 15:47 UTC, markconroy commented
@msayoung @stephen-cox this PR is updated now to check for the field before acting on it.

Do we want to add this field to existing installs as well as new installs?

2024-12-17 11:30 UTC, msayoung approved these changes

2024-12-17 11:44 UTC, stephen-cox commented
I will leave the decision on whether to add this to existing installs to someone else, but I not it's not straightforward to add is manually so might be good to push it out if it's useful.

Looks fine to me now, but before we can merge this we'll want all the tests passing.

2024-12-17 11:53 UTC, msayoung commented
Also just tested and working fine. Good question about existing sites, I agree that probably yes ...?

2024-12-17 12:22 UTC, stephen-cox commented
Discussing at Merge Tuesday - would a site wide setting for this be better?

2025-01-07 12:31 UTC, finnlewis commented
@markconroy do you think a site wide setting would be better here?

2025-03-04 12:22 UTC, closed without merging

2025-03-04 12:22 UTC, markconroy commented
Closing this, as we now have a sitewide setting instead.