Fix fatal error if overview not loaded
localgovdrupal/localgov_guides pull request #29
Opened 2020-10-29 16:34 UTC by tanc

Fix #28 by adding using getEntity() to load the overview rather than the magic method.
Adds a condition that the overview is not empty to protect for future issues.

2020-10-29 16:44 UTC, tanc commented on src/EventSubscriber/PageHeaderSubscriber.php
> +      if (!empty($overview) {
Missing closing bracket

2020-10-29 16:46 UTC, tanc commented on src/EventSubscriber/PageHeaderSubscriber.php
> +      if (!empty($overview) {
Fixed

2020-11-04 18:34 UTC, finnlewis commented
Hi @andybroomfield @Adnan-cds 
Any chance one of you can review this and approve, just to make sure we're maintaining the separate organisation peer review of pull requests as planned?
Many thanks,
Finn

2020-11-04 18:39 UTC, Adnan-cds commented
I am not entirely getting what the original code was doing and what the changed version is doing.  Sorry, probably just need a break :(  I have added Steve who wrote the original code.  If Steve is happy, I am happy for this to be merged.

FAO @stephen-cox

2020-11-05 01:48 UTC, andybroomfield requested changes
Doing a quick look through, the change is fine.
However I noticed there is no tests for the pageHeader with guides. Given the specialist behaviour we should have a test to verify the pageHeader is outputting the parent guide title and description.

2020-12-07 13:45 UTC, tanc commented
@andybroomfield tests would be good! It would have picked up that `getEntity()` was (somehow) loading the same entity and not the referenced one. I've updated it to use `$event->getEntity()->localgov_guides_parent->entity;` which correctly loads the parent guide page and displays the correct title.

2020-12-07 15:53 UTC, andybroomfield commented
Thanks @tanc. Are you able to write and commit a test aswell or do you need help with that.

2020-12-07 15:56 UTC, tanc commented
@andybroomfield I probably won't have time to get a test in due to sprinting on other things and I'm not set up with tests (yet) on this project. If I get some time I'll see if I can write something.

2020-12-08 09:36 UTC, andybroomfield commented
ok @tanc I will see if I can take over this branch and write a test.

2020-12-08 17:22 UTC, andybroomfield commented
Added a PR with a test in #32.
That should merge with this branch.

2020-12-14 07:27 UTC, tanc commented
I suggest we close this in favour of #32 which contains the code in this PR

2020-12-14 08:59 UTC, closed without merging